name: Deploy to GitHub Pages

on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3.3.0
      with:
        node-version: 16.x

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy Test Results
      uses: JamesIves/github-pages-deploy-action@v4.3.4
      with:
        branch: gh-pages 
        folder: build 
        single-commit: true
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com
        token: ${{ secrets.GITHUB_TOKEN }}